name: iOS Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Useful to see which Xcode is on the runner
      - name: Show Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Build & Test (Simulator)
        run: |
          set -o pipefail
          xcodebuild \
            -project SwiftAcademy.xcodeproj \
            -scheme SwiftAcademy \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            test | xcpretty
