name: SwiftLint

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint (SwiftLint)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint (warnings fail the job)
        run: swiftlint --config .swiftlint.yml --reporter github-actions-logging --strict
